.travis.yml, polymorphic/query.py, polymorphic/query_translate.py, tox.ini
Hi,
Here  is a proposal to add Django 1.8 support to *django-polymorphic*.
=> Django 1.8 alpha support

polymorphic/tests.py
- Remove diamond inheritance tests since these test a bug in Django,
not in django_polymorphic.
- Fix spurious print message in test_primary_key_custom_field_problem(),
where uuid instances are for some reason being compared to uuid.UUID
classes. Replaced with a test that checks that the primary key values
are valid UUIDs.
- Remove Django > 1.6 conditionals wrapping the multiple inheritance
tests and model definitions, in favor of using the definitions for
Django 1.7. Django 1.7 requires a custom primary key when using concrete
model inheritance because failing to do so is potentially ambiguous. Adding
the custom primary key does not break tests in older Django versions.
=> Cleanup tests by removing spurious errors and unnecessary noise

polymorphic/query.py
=> Fix Pickle exception when polymorphic model is cached

polymorphic/query.py, polymorphic/query_translate.py, polymorphic/tests.py
closes https://github.com/chrisglass/django_polymorphic/issues/213
It's a fairly simple PR. I haven't tried to investigate how to clone Q objects in Django 1.4/1.5 yet. Any ideas?
=> Issue #213: Don't modify Q passed in as arguments

docs/third-party.rst, polymorphic/contrib/guardian.py, polymorphic/tests.py
=> Add helper function for django-guardian.

polymorphic/admin/childadmin.py
This change fixes an issue where django-polymorphic raises a
`ParentAdminNotRegistered` exception when you register an admin for a
child model ancestor, but not for the root ancestor as pointed to by
the `polymorphic_ctype` field. This error occurs only when you *Save*
the child model detail form, not when you *Save and continue* on that
same form.
This situation occurs for us when using django-fluent-pages version
1.0.1 which has an intermediate `Page` model registered with a parent
admin to show the pages listing. The existing `_get_parent_admin` method
expects an admin to be registered for the root `UrlNode` model pointed
to by the `polymorphic_ctype` field.
This fix uses a potentially naive and slow brute-force approach where
it walks up the class hierarchy and checks  whether a …
=> Fix get parent admin when intermediate not root ctype model is registered

polymorphic/static/polymorphic/css/polymorphic_inlines.css
=> Added 'z-index' attribute to '.polymorphic-type-menu' CSS class

.travis.yml, polymorphic/query.py
I'm a little concerned that this loses some of the efficiencies (in particular, chunking) from previous versions. That's something that can surely be improved.
This addresses #267.
=> WIP: Get tests running on django 1.11

.travis.yml, polymorphic/tests/migrations/0001_initial.py, polymorphic/tests/models.py, polymorphic/tests/test_admin.py, polymorphic/tests/test_contrib.py, polymorphic/tests/test_multidb.py, polymorphic/tests/test_orm.py, polymorphic/tests/test_regression.py, polymorphic/tests/test_utils.py, runtests.py, tox.ini
Travis seems to have given up building my branch, so opening a PR early for that. Feedback is also welcome though.
Note: I'll rebase this once it works as expected.
Update: Closes #282
=> Run CI with postgres too

polymorphic/locale/en/LC_MESSAGES/django.po
=> removed unnecessary comments

polymorphic/static/polymorphic/js/polymorphic_inlines.js
=> Fix bug #392 "Inline model admin: wrong hiding of add button"

polymorphic/query.py, polymorphic/tests/test_orm.py
=> Issue #373 : Fix bug with get_real_instances on empty base_result_objects

polymorphic/contrib/extra_views.py
=> Restore compatibility with current versions of extra-views (issue #367).

polymorphic/tests/test_orm.py
Use the provided get_deferred_fields() method instead of relying on the
repr() for the objects to determine whether a field is deferred or not.
This is an attempt at fixing the flaky travis runs (since I assume repr() relies on dict ordering somehow, although I have not checked).
=> Make test_defer_fields use get_deferred_fields()

.travis.yml, AUTHORS.rst, setup.cfg
- Adding in AUTHORS file
- Fix minimal Django version in setup
- Remove deprecated options in travis config
=> [misc] Various cleanup

polymorphic/base.py
=> Make it possible to use custom keyword args in model class definition

polymorphic/formsets/models.py
=> Pass `widgets` field to `modelform_factory`

polymorphic/formsets/models.py
=> Use TypedChoiceField for polymorphic_ctype field

polymorphic/admin/childadmin.py
Fix for error in https://github.com/django-polymorphic/django-polymorphic/pull/539
Restore for loop so the code works correctly again. This is exactly how it works in my code I overriden in my subclass.
Sorry for that :(
=> Fix for broken fix about multi-fields in single line

CONTRIBUTING.rst, README.rst
https://github.com/jazzband/django-polymorphic/issues/553
=> Add contributing doc and badge

example/pexp/management/commands/p2cmd.py, example/pexp/management/commands/polybench.py, polymorphic/admin/childadmin.py, polymorphic/admin/filters.py, polymorphic/admin/helpers.py, polymorphic/admin/inlines.py, polymorphic/admin/parentadmin.py, polymorphic/base.py, polymorphic/formsets/generic.py, polymorphic/formsets/models.py, polymorphic/managers.py, polymorphic/models.py, polymorphic/query.py, polymorphic/query_translate.py, polymorphic/showfields.py, polymorphic/tests/admintestcase.py, polymorphic/tests/test_orm.py
Guided by `ruff --select=UP` + [`flynt`](https://github.com/ikamensh/flynt/), hand-checked afterwards.
=> Replace string interpolation and .format calls with f-strings

polymorphic/base.py, polymorphic/compat.py, polymorphic/formsets/utils.py, polymorphic/models.py, polymorphic/query.py, polymorphic/query_translate.py, polymorphic/tests/models.py, polymorphic/tests/test_orm.py, polymorphic/tests/test_regression.py
This PR removes the Python and Django version checks that aren't necessary anymore.
=> Remove unnecessary version checks
