jazzband/django-polymorphic

polymorphic/base.py
polymorphic/tests.py

Fixes #96 (_default_manager cannot be accessed on a model instance).
Using `model_cls.add_to_class()` calls `Manager.contribute_to_class()`, which then sets the attribute to an instance of `ManagerDescriptor`. In the case of `_default_manager`, this behavior differs from Django's, as `_default_manager` is set to the manager instance itself, not its descriptor. This is why it is normally possible to access `default_manager` from a model instance.

Set _default_manager directly on model_cls; don't use add_to_class()

---

polymorphic/query.py
polymorphic/tests.py

There is currently a bug when inheriting from a PolymorphicModel with a custom primary key. For example, with the following models:
```python
class CustomPkBase(ShowFieldTypeAndContent, PolymorphicModel):
b = models.CharField(max_length=1)
class CustomPkInherit(CustomPkBase):
custom_id = models.AutoField(primary_key=True)
i = models.CharField(max_length=1)
```
The following code results in a queryset that is missing items:
```python
CustomPkBase.objects.create(b='b')
CustomPkInherit.objects.create(b='b', i='i')
print(len(CustomPkBase.objects.all())) # expected: 2; actual value: 1
```
This pull request adds tests in the first commit (which fail), and then fixes those tests in the second commit. I believe that this pull request fixes #66.

Bug with queryset results on base model where child model has a custom primary key

---

polymorphic/admin.py

The problem occurs when you have a filter and create o delete a child, when is back to change list
the filter is lost, and have a e=-1 as a get parameter

Fixed preserved filter for django 1.7

---

polymorphic/admin.py

I get a 500 error when I try to load id without a trailing slash (i.e. /admin/app/parentmodel/id ). This fixes the issue.

Don't remove '/' from id when it's not in the path

---

polymorphic/polymorphic_model.py

Django 1.8b2 complains that the related name defined on polymorphic_ctype is not valid (due to this commit: django/django@1e5e2a470).
It requires either a valid Python identifier, or for the name to end in a '+'... so I added a '+' at the end.
Alternatively the period will have to be removed from the related name, and replaced with an underscore or something.
What do you think?

Issue with related_name in polymorphic_ctype field

---

docs/admin.rst

Updates the example code in the admin section of the docs to reflect that "base_model should be set in [the child model admin] class as well." For those of us who don't read unless absolutely forced to...

add base_model declaration to child models in admin docs example (docfix)

---

polymorphic/admin.py

Using the `AdminSite` class directly can cause issues when the parent
model is registered with a custom admin site class.
For example in my project I have a custom `User` model that doesn't have an `is_staff` flag. Since the `AdminSite.has_permission` method uses this flag, I had to override it in a custom admin site class. Now when `real_admin.change_view` is called, an error is raised because the original `AdminSite.has_permission` is executed instead of my custom method.

Use parent admin site class for child admin site

---

polymorphic/admin.py

When visiting the change form for a polymorphic model and providing a bogus primary key, we currently get a 500 error `ObjectDoesNotExist`. This change raises `Http404` instead.

Raise Http404 if object does not exist.

---

polymorphic/polymorphic_model.py

- SingleRelatedObjectDescriptor was renamed in Django 1.9
- Periods are not allowed in related_names

Django 1.9 Fixes

---

.travis.yml

Django's latest 1.8.X minor supports Python 3.5.

Test Django 1.8 with Python 3.5

---

docs/admin.rst

I stumbled upon this and figured it out by checking the issue tracker. It should be mentioned in the docs that non-int pks require additional work to work properly.

Mention pk_regex in docs when using non-int pk

---

docs/quickstart.rst

The changelog states that 1.9 is supported, but the quickstart document has not yet been updated.

Update quickstart for Django 1.9 compatibility

---

polymorphic/query.py
polymorphic/tests.py

This fixes [171](https://github.com/chrisglass/django_polymorphic/issues/171).
It allows using complex expressions in aggregate/annotate on a PolaymorhicQueryset like:
```
MyModel.poly_manager.aggregate(cnt=Count(Case(When(some_field=1, then=1))))
```

Support for Django 1.8 complex expressions in annotate/aggragte

---

polymorphic/tests.py

Test for #201 
I checked that without commit 88922d7d5e918f1338eeb9baeecb17ed98ed1261, the test fails.
I'm waiting for travis to see if it works on all django versions.

Test that expressions are supported

---

polymorphic/managers.py
polymorphic/tests.py

These changes prevent the query sets on 'proxy' models from including
the items from the 'super-class'.
I'm not really sure if it is as simple as these change suggest, but...

Issue #200 - Exclude super-class from proxy model query sets

---

docs/admin.rst
polymorphic/admin.py

I took #58 and reimplemented it on current HEAD without removing any of the old code. This means that it is fully backwards compatible.
I am not sure what to do with DeprecationWarning which I added because python hides this by default and I couldn't find any way to make it visible when running the usual ```manage.py runserver```.
Also let me know if I should add something to Changelog. Although text from #58 could be reused I guess.

Admin refactoring (based on #58)

---

polymorphic/admin/childadmin.py

Since it's possible to have parent model also as a child model in ```child_models``` list, in compatibility mode ```_get_parent_admin``` will do a roundtrip in such case (first it will find parent model's PolymorphicChildAdmin, and on the second call will return super of that PolymorphicChildAdmin subclass). So when in compatibility mode and parent model is among child models, ```_get_parent_admin``` will return super of child admin (not super of parent admin, which happens in all other cases), but it works fine because response_post_save methods redirect to same urls :)

Fix redirects after child model add/change in PolymorphicChildModelAdmin

---

polymorphic/managers.py
polymorphic/query.py
polymorphic/tests.py

- Pass hints to returned queryset in `PolymorphicManager.get_queryset()`.
- Use `self.db` instead of `self._db` in `PolymorphicQuerySet`.
- Add unit tests for related object queries using non-default databases.
Fixes #220.

#220 Pass hints to returned queryset in PolymorphicManager.get_queryset.

---

README.rst
docs/third-party.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

.travis.yml
runtests.py

This patch runs enables Travis tests in Django development (with allow failures) to show the errors of current codebase with Django 1.10 (i.e. #225).
It also contains correction for new templates handling in tests in Django 1.10

Test in development Django version (with allow failures)

---

polymorphic/static/polymorphic/css/polymorphic_inlines.css

Prevent div.polymorphic-add-choice overlapping previous inline formset when using Grappelli.
Also tested without Grappelli.

CSS tweak for Grappelli

---

docs/third-party.rst

There was a mistake with the `GUARDIAN_GET_CONTENT_TYPE` setting in the django-guardian integration docs. I've also re-worked the explanation to make it more clear.

Improve django-guardian integration docs.

---

polymorphic/formsets/models.py

In Python 3.4 trying to generate a polymorphic_inlineformset results in a TypeError with the following message: "'KeysView' object does not support indexing". This solves that problem by ensuring that `child_models` is a list, and thus can be referenced by index.

Wrap call to key() in list() so it can be indexed

---

.travis.yml
polymorphic/tests/__init__.py
polymorphic/tests/test_orm.py
tox.ini

This builds django-polymorphic against python 3.6 and django 1.11b1.
The new version of python works fine, but django 1.11 fails.
~~The test suite now runs checks, and it seems to be failing on one of them:~~
~~`polymorphic.MRODerived: (models.E005) The field 'id' from parent model 'polymorphic.mrobase3' clashes with the field 'id' from parent model 'polymorphic.mrobase1'.`~~ 
~~Once that's addressed, I suspect we're going to get a little closer to the cause of #267.~~
Ok, fixed that, now we're seeing #267.

Test against django 1.11(b1) / python 3.6

---

docs/_ext/djangoext/docstrings.py

`force_unicode` has been [deprecated](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.encoding.force_unicode) and replaced with `force_text`[0].
Furthermore, `force_unicode` is not available in Python3, causing the
documentation to be unbuildable with Python3 sphinx.

Replace force_unicode with force_text for Python3 compatibility.

---

docs/_ext/djangodummy/settings.py

This is merely cosmetic to avoid Django warning because of
`django.contrib.contenttypes` being referenced but not an installed app.

Install django.contrib.contenttypes for docstrings.

---

.travis.yml

Django 2.0 will be dropping support for python 2, so there's no point in running the tests in that combination.

Don't test Django's master on python 2

---

polymorphic/models.py

At this point, we don't know why this line of code is executed, but
we do know it's not consistently executed between Django 1.10 and
Django 1.11 due to the addition of `ForwardOneToOneDescriptor`, a
subclass of `ForwardManyToOneDescriptor`.
Refs. 6628145af7e894f6977e3a14a713ac14449f3a4e
Refs. dj-stripe/dj-stripe#524
Refs. django/django@38575b007a722d6af510ea46d46393a4cda9ca29

Fix accessor replacement consistency on Django 1.11

---

polymorphic/locale/en/LC_MESSAGES/django.po
polymorphic/locale/fr/LC_MESSAGES/django.po

We're using django-rosetta which uses polib to parse PO files and it fails with django-polymorphic's en/fr PO files resulting in SyntaxError.
This applies to both `#msgid` and `#msgstr` entries and problem lies that comments in PO files should have space after `#` character, otherwise they're handled as unknown token, thus SyntaxError.
This PR fixes the problem.

Fixed PO files which resulted in SyntaxError when parsed by polib

---

polymorphic/base.py
polymorphic/tests/__init__.py
runtests.py

This is so because polymorphic tries to validate manager on a swapped model while such manager is inaccessible (described in detail in #270)

Swapped polymorphic models don't work on Django>=1.10

---

.travis.yml
polymorphic/__init__.py
polymorphic/admin/childadmin.py
polymorphic/admin/helpers.py
polymorphic/admin/parentadmin.py
polymorphic/base.py
polymorphic/formsets/generic.py
polymorphic/formsets/models.py
polymorphic/manager.py
polymorphic/managers.py
polymorphic/models.py
polymorphic/query.py
polymorphic/query_translate.py
polymorphic/showfields.py
polymorphic/tests/test_orm.py
polymorphic/tests/test_utils.py
setup.cfg
setup.py
tox.ini

This PR does a few things. In the first two commits:
- We no longer test on versions of Django and Python which are no longer supported.
- Remove all pre-django 1.8 hacks.
Then, in a separate commit, we remove support for Django 1.8 as well. I kept this separate because I may understand the argument to keep Django 1.8 as it is still supported upstream... *however*, Django 1.11 is the new LTS and, given the complexity of django-polymorphic and the amount of hacks dropping 1.8 removes, I would *very highly* recommend dropping 1.8 support as well, and recommend django-polymorphic==1.2 to Django 1.8 users.
As a followup to this, I am also improving compatibility with Django 2.0, to the point that tests now pass on django-dev. I cannot vouch for their reliability, however, especially given …

Django compatibility cleanups and fixes

---

polymorphic/tests/test_orm.py
polymorphic/tests/test_utils.py

Several tests were failing with django master. This is because, apparently, `id`s don't match those expected in tests, and other test-related details.
Replace all test comparisons with `assertQuerysetEqual`, which is safer and cleaner for the sort of comparison we're doing.
Fixes #310

Fix failing tests with django/master

---

polymorphic/admin/helpers.py

Allowing variable-length arguments in `get_inline_formsets` of `PolymorphicInlineSupportMixin` to fix compatibility with other admin extensions.
For example, when used alongside [django nested admin](https://github.com/theatlantic/django-nested-admin), we see the following error:
`get_inline_formsets() got an unexpected keyword argument 'allow_nested'`
This change simply ignores any extra arguments passed in by these other mixins.

Simple fix for compatibility with other admin extensions

---

polymorphic/query.py
polymorphic/tests/__init__.py
polymorphic/tests/test_orm.py

When using .defer on a PolymorphicQuerySet with multiple childs that
subclass from the same polymorphic parent model yield an error like:
```
>>> Base.objects.defer('ModelY___field_y')
Traceback (most recent call last):
...
FieldDoesNotExist: ModelX has no field named 'field_y'
```

fix error with .defer and child models that use the same parent

---

docs/changelog.rst
polymorphic/admin/childadmin.py

`ModelAdmin.declared_fieldsets` property was removed in Django 1.9. Checking `fieldsets` and `fields` is equivalent and will actually make that `if` do it's work.

Do not use deprecated and removed declared_fieldsets attribute in admin

---

polymorphic/admin/childadmin.py

Sorry for this mess. The checks for `fields` and `fieldsets` were completely wrong in the previous PR (which you fixed, albeit with a typo 'or or').
Also, the "prevent infinite recursion" lines that I deleted are actually necessary. So I restored that with correct fields/fieldsets check now.

Admin fieldsets fix (another attempt)

---

polymorphic/query.py
polymorphic/tests/migrations/0001_initial.py
polymorphic/tests/models.py
polymorphic/tests/test_orm.py

Related issue: django-polymorphic/django-polymorphic#204
This implementation just invokes `pre_save_polymorphic` method from `PolymorphicModel` for each saving object just before django's `bulk_create` . Usually this method is used in `save` method implementation in `PolymorphicModel`. Particullary `pre_save_polymorphic` method checks that foreign key to `ContentType` is set. If not, sets it.
Other possible solution (I didn't test it) is `moving pre_save_polymorphic` call to `__init__` in `PolymorphicModel` and removed this call from save method. In this case overidded `bulk_create` won't exist

Bulk create support

---

.travis.yml
README.rst
docs/changelog.rst
docs/quickstart.rst
polymorphic/admin/parentadmin.py
polymorphic/formsets/utils.py
polymorphic/models.py
polymorphic/tests/admintestcase.py
polymorphic/tests/models.py
polymorphic/tests/test_orm.py
setup.cfg
tox.ini

This fixes a few minor issues to add support for django 2.0(b1).
I have:
- Removed django 1.10 from the test suite in the process, ~but have not yet dug out compat fixes that were added for it~.
- Removed three models from the tests that were never referenced in the tests.
- Not yet tested this manually.
There is one remaining unaddressed `RemovedInDjango20Warning`, but I've had some frustration with it. See https://code.djangoproject.com/ticket/28750
TODO:

Add django 2.0 support

---

polymorphic/query.py

Long story short:
* We use django-polymorphic with django-cacheops
* Considering models: `Content` - parent and `Movie` - child
* Content has boolean `published` field
1. Fetching `Content.objects.get(pk=pk)` caches Movie object as content.
2. Fetching `Content.objects.non_polymorphic().get(pk=pk)` receives Movie object from cache, while expecting Content object only.
3. Changing `movie.published` invalidates with value for all Movie cache entries, but not Content one because of unexpected model class.
The solution is to cache polymorphic and non-polymorphic versions separately. This can be done with replacing `qs._iterable_class` to default Django's (cacheops respects `_iterable_class` when computes cache key).

replace iterable class in qs.non_polymorphic

---

polymorphic/models.py
polymorphic/tests/models.py
polymorphic/tests/test_orm.py

Enhancement for  #202 where a `TypeError` is caused by an invalid content type id.
This change allows that scenario to raise the `PolymorphicTypeInvalid` exception making the issue explicit.

Raise `PolymorphicTypeInvalid` instead of cause `TypeError`

---

polymorphic/query.py
polymorphic/tests/test_orm.py

I stumbled upon https://github.com/django-polymorphic/django-polymorphic/issues/68 which causes some errors for us. As mentioned in the issue, the problem is cause by reusing the instances stored in base_result_objects_by_id. This PR tries to work around it by maintaining the lists differently which allows to make shallow copies of the real instances (see line 417). Feel free to test!

Fix prefetch_related behavior

---

polymorphic/admin/parentadmin.py

Instead of querying the database for every content type, we can simply get them in one query.

Performance improvement on parentadmin

---

polymorphic/admin/childadmin.py
polymorphic/admin/filters.py
polymorphic/admin/forms.py
polymorphic/admin/helpers.py
polymorphic/admin/parentadmin.py
polymorphic/templatetags/polymorphic_formset_tags.py

ugettext* is an alias for gettext since django 2.0
Fix #424 
Fix #443

Replace ugettext with gettext to fix deprecation warnings

---

polymorphic/admin/parentadmin.py

In some cases (mine :P) self.get_child_type_choices(request, "add") returns [], so this case must be handled.

PolymorphicParentModelAdmin.add_type_view edge case

---

polymorphic/admin/helpers.py
polymorphic/admin/parentadmin.py
polymorphic/templatetags/polymorphic_formset_tags.py

Use force_str instead of force_text (deprecated in Django 3.2, removed in Django 4.0)

Django 4.0a compatibility

---

docs/contributing.rst

As I was preparing to create pr #488 I was reviewing the contribution guidelines and noticed that the python versions were pretty out of date compared to the information in tox.
This just updates the documentation.

Update Python Versions in Documentation

---

polymorphic/query.py
polymorphic/tests/test_orm.py

This simple pull requests converts the `batch_size` parameter on the `bulk_create` method into `**kwargs`. Django supports two keyword arguments: `batch_size` and `ignore_conflicts`, the latter of which was added with Django 2.2.
The `ignore_conflicts` parameter instructs supported databases to ignore the failure to insert rows that fail constraints. This is especially useful if you're running `bulk_create` with a large number of objects that may or may not exist.
I've added two tests; one with the `ignore_conflicts` set to `True` and one with it set to `False`. I'm checking to see whether the insertion happens when one object exists and one does not.
I decided to go with `bulk_create(self, objs, **kwargs)` instead of `bulk_create(self, objs, batch_size=None, ignore_errors=False)` to make …

Allow for kwargs to be passed to bulk_create

---

polymorphic/models.py
polymorphic/tests/migrations/0001_initial.py
polymorphic/tests/models.py
polymorphic/tests/test_orm.py

Hello Folks, 
Here is my proposal to fix #9. 
When we have a PolymorphicModel with a non-polymorphic parent, deleting the parent is missing `_base_objects`. This pull-requests ads a fallback to `objects` when `_base_objects` is None. 
Cheers!

Non polymorphic parent

---

polymorphic/query_translate.py

With installed `django-advanced-filters` app, filter polymorphic model return `Q` object child list, not tuple.

Q object child is a list or tuple

---

polymorphic/admin/childadmin.py

The request.path isn't the correct path to match the url patterns with is it? Shouldn't this use reqeust.path_info so that if someone's application is hosted as a subdirectory you will still be matching the correct portion of the path in the django urls?
With this code in its present state any admin integration will bring my application down.

Fix for projects which might have a different base_url or script_name.

---

docs/advanced.rst

Replaced legacy `--natural` flag which does not exist in django anymore with `--natural-foreign` and `--natural-primary`

Update docs: Replace legacy argument with updated arguments

---

polymorphic/__init__.py
setup.cfg

Fixes #503 
`pkg_resources` is deprecated and should not be used anymore. We encountered this in our CI see https://github.com/django-json-api/django-rest-framework-json-api/pull/1146
The version is now defined in `polymorphic/__init__.py` and `setup.py` extracts it from there. This way, there is also no need for setuptools to be installed when using django polymorphic.

Removed usage of deprecated pkg_resources

---

polymorphic/static/polymorphic/css/polymorphic_inlines.css

**Problem**
Polymorphic menu are light in dark mode. Here is a screenshot I am attaching.
**Solution**
Updated polymorphic_inlines.css to override colors using the 'prefers-color-scheme: dark' media query.
This is a screenshot after changes are done.

Add css dark mode to polymorphic_inlines.css

---

polymorphic/admin/childadmin.py

As [Django documentation](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets) states, you may use:
```python
{
"fields": [("first_name", "last_name"), "address", "city", "state"],
}
```
to specify that `first_name` and `last_name` should be displayed in single line.
Django Polymorphic though wasn't able to work with this syntax properly as it tried to remove whole tuple instead of individual elements from child fields.
This PR fixes this, and now multi-field lines are rendered correctly.

Fix multi-fields in single line

---

.github/workflows/ci.yml
.pre-commit-config.yaml
polymorphic/admin/filters.py
polymorphic/base.py
polymorphic/query_translate.py
pyproject.toml
setup.py

This PR switches linting/formatting from flake8 + isort + black to [ruff](https://ruff.rs/) and its formatter.
It also adds a simple GitHub Actions step to run that linting.
The examples and tests are exempt from some of the lints for now, to keep the diff here manageable.

Lint and format with ruff

---

.github/workflows/test.yml
pyproject.toml
setup.cfg
tox.ini

Drop support for non-supported versions of Django and Python

---

.github/workflows/test.yml
docs/contributing.rst
tox.ini

This fixes the coverage upload to Codecov.
```
Run codecov/codecov-action@v3
==> linux OS detected
https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (b9282b8b43eef83f722646d8992c4dd36563046afe0806722184e7e9923a6d7b  codecov)
==> Running version latest
==> Running version v0.7.1
/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov -n  -Q github-action-3.1.4 -s /tmp/coverage
[2023-[12](https://github.com/hugovk/django-polymorphic/actions/runs/7274100648/job/19819330547#step:8:13)-20T10:28:21.532Z] ['info'] 
_____          _
/ ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
\_____\___/ \__,_|\___|\___\___/ …
```

Fix coverage: use default file locations

---

polymorphic/query.py

This PR ensures that test___lookup only processes non-None source_expression values to prevent potential NoneType errors. The change adds a simple condition to check if source_expression is None before passing it to test___lookup.
Added a None check for source_expression before calling test___lookup.
Why this is needed:
- Prevents potential NoneType errors when evaluating query expressions.
- Ensures test___lookup is only invoked with valid values.
- Our unit tests start failing after migrating from Django 5.0.10 to 5.1.5 and start showing "AttributeError: 'NoneType' object has no attribute 'name'"
- Inspired by [this fix](https://github.com/jazzband/django-polymorphic/commit/88922d7d5e918f1338eeb9baeecb17ed98ed1261), which addressed a similar issue in django-polymorphic.

PolymorphicQuerySet: Prevent NoneType error in test___lookup

---

polymorphic/static/polymorphic/css/polymorphic_inlines.css

More recent versions of Django admin use CSS variables to control the theming color, allowing a user to chose their color scheme independently from their preferred one. Previously, django-polymorphic supported different color schemes only via the `prefers-color-scheme` media query. This commit implements usage of CSS variables for colors, ensuring consistent compatibility with the rest of the admin interface.

Use CSS variables for colors

---

polymorphic/base.py
polymorphic/query.py
polymorphic/showfields.py

CI currently crashes with ruff complaining about the use of == to compare types. This breaks CI on unrelated PRs.

Fix use of is and is not vs. ==

---

polymorphic/models.py
polymorphic/tests/test_orm.py

Fixes a bug where `PolymorphicModel`'s `get_real_instance()` raises an exception when `get_real_instance_class()` returns None.

Check for None on real_model in get_real_instance

---

polymorphic/query.py
polymorphic/tests/migrations/0001_initial.py
polymorphic/tests/models.py
polymorphic/tests/test_orm.py

picking up from #638 b/c branch permissions issues.

Add aggregate query on empty tables tests for dj 5.1+ compat

---

.github/workflows/test.yml
setup.cfg
tox.ini

Python 3.8 has been EOL since October 2024.
This drops Python 3.8 from CI, and also adds the `python_requires` marker to declare 3.9+ is the only way to go.

Drop support for Python 3.8
